### PR TITLE
Provide an allocation free API

### PR DESCRIPTION
**Pull request by simonwittber**

### CODE REVIEW

**Comment by vis2k** [comment]
Thanks for the PR, will consider it.
Main goal of Telepathy is simplicity & reliability, I can't promise that we will ever worry about allocations because that usually makes the code more complicated.

**Comment by simonwittber** [comment]
Thanks. Once the [obsolete] methods are removed, it looks very similar to the original code. I've also made the required changes to Mirror, which I'll also share if you need.

**Comment by saguiitay** [comment]
Having an allocation-free API is critical. Reducing allocations is one of the key factors in improving performance in servers (e.g. RavenDb, ASP.Net, etc.)

**Comment by TimPickup** [comment]
I would also say its important to not do unnecessary allocations imo

**Comment by paulpach** [comment]
We do not consider it "critical",   it is nice to have,  but not if it makes the code uglier.
On a network library,  the bottleneck is the actual network,   not allocations.

My suggestion is that you either:
1) Post actual benchmarks that show allocations in telepathy are a significant problem
2) fork the code and maintain an allocation free API for yourself.

**Pull request closed without merging**
