### PR TITLE
Server ReceiveTimeout support

### PR DESCRIPTION
**Pull request by YuriPetskus**
In my game initially spawned several thousand objects. Server without support ReceiveTimeout goes into an eternal wait. That is, the following events are not received, including OnPlayerReplace(). 
Offer the option of implementing support for the ReceiveTimeout for the server

### CODE REVIEW

**Comment by MichalPetryka** [comment]
Don't change the intendation

**Comment by vis2k** [comment]
@YuriPetskus can you explain further?
the problem with ReceiveTimeout is that Telepathy is meant to block on Receive until something comes in. a ReceiveTimeout would mean 'if nothing came in after 10 seconds then disconnect'.

**Comment by YuriPetskus** [comment]
> @YuriPetskus can you explain further?
> the problem with ReceiveTimeout is that Telepathy is meant to block on Receive until something comes in. a ReceiveTimeout would mean 'if nothing came in after 10 seconds then disconnect'.

The 10 seconds timeout does not work. 
The server does not interrupt the connection and does not receive any messages.

**Comment by YuriPetskus** [comment]
Actually, client need RecieveTimeout too.

**Comment by vis2k** [comment]
closing for now. please explain why we need this, I still don't fully understand the use case.

**Pull request closed without merging**
